[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["aecsocket <aecsocket@tutanota.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/aecsocket/const-exhaustive"
rust-version = "1.81.0"
version = "0.1.0"

categories = [] # TODO replace
keywords = []   # TODO replace

[workspace.lints.rust]
missing_docs = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

[workspace.dependencies]
const-exhaustive-derive = { version = "0.1.0", path = "crates/const-exhaustive-derive" }

generic-array = "1.1.0"
typenum = "1.17.0"

proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = "2.0.77"
