on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt,clippy,miri
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall --no-confirm just typos-cli cargo-shear
      - run: curl -fsSL https://tombi-toml.github.io/tombi/install.sh | sh
      - run: just test
